import type { CatalogPool } from '@/catalog/types';

export const catalogPools = [
  {
    id: 'tent_main',
    categoryId: 'shelter_rest',
    label: 'Tienda',
    type: 'essential',
    priority: 'high',
    conditions: {
      accommodationIn: ['tent'],
    },
    itemIds: ['tent_main_body', 'tent_poles', 'tent_bag'],
  },
  {
    id: 'ground_rain_protection',
    categoryId: 'shelter_rest',
    label: 'Protección de suelo y lluvia',
    type: 'conditional',
    priority: 'high',
    conditions: {
      accommodationIn: ['tent'],
    },
    itemIds: ['ground_tarp', 'rainfly_main'],
  },
  {
    id: 'tent_setup_kit',
    categoryId: 'shelter_rest',
    label: 'Kit de anclaje y montaje',
    type: 'essential',
    priority: 'high',
    conditions: {
      accommodationIn: ['tent'],
    },
    itemIds: ['stakes_set', 'guy_lines', 'camp_mallet'],
  },
  {
    id: 'shade_privacy',
    categoryId: 'shelter_rest',
    label: 'Sombra o privacidad',
    type: 'extra',
    priority: 'low',
    conditions: {
      accommodationIn: ['tent', 'caravan'],
      tripDurationIn: ['medium', 'long'],
    },
    itemIds: ['shade_tarp', 'privacy_screen', 'extra_guylines'],
  },
  {
    id: 'sleeping_bag',
    categoryId: 'shelter_rest',
    label: 'Saco de dormir',
    type: 'essential',
    priority: 'high',
    conditions: {
      accommodationIn: ['tent', 'caravan'],
    },
    itemIds: ['sleeping_bag_main', 'sleeping_bag_liner'],
  },
  {
    id: 'sleeping_pad',
    categoryId: 'shelter_rest',
    label: 'Aislante o colchoneta',
    type: 'conditional',
    priority: 'high',
    conditions: {
      accommodationIn: ['tent'],
    },
    itemIds: ['sleeping_pad_main', 'inflation_pump'],
  },
  {
    id: 'camp_pillow',
    categoryId: 'shelter_rest',
    label: 'Almohada',
    type: 'essential',
    priority: 'medium',
    conditions: {
      accommodationIn: ['tent', 'caravan', 'bungalow', 'camping_cabin'],
    },
    itemIds: ['camp_pillow_main', 'pillow_cover'],
  },
  {
    id: 'comfort_bed',
    categoryId: 'shelter_rest',
    label: 'Ropa de cama ligera',
    type: 'conditional',
    priority: 'medium',
    conditions: {
      accommodationIn: ['caravan', 'bungalow', 'camping_cabin'],
    },
    itemIds: ['light_sheet_set', 'light_blanket'],
  },
  {
    id: 'hammock',
    categoryId: 'shelter_rest',
    label: 'Hamaca',
    type: 'extra',
    priority: 'low',
    conditions: {
      tripDurationIn: ['medium', 'long'],
    },
    itemIds: ['hammock_main', 'tree_straps'],
  },
  {
    id: 'stove',
    categoryId: 'cooking_food',
    label: 'Hornillo',
    type: 'conditional',
    priority: 'high',
    conditions: {
      accommodationIn: ['tent', 'caravan'],
    },
    itemIds: ['stove_main'],
  },
  {
    id: 'fuel',
    categoryId: 'cooking_food',
    label: 'Combustible',
    type: 'conditional',
    priority: 'high',
    conditions: {
      accommodationIn: ['tent', 'caravan'],
    },
    itemIds: ['fuel_canister'],
  },
  {
    id: 'fire_starting',
    categoryId: 'cooking_food',
    label: 'Encendido de fuego',
    type: 'conditional',
    priority: 'medium',
    conditions: {
      accommodationIn: ['tent', 'caravan'],
    },
    itemIds: ['lighter_main', 'waterproof_matches', 'fire_starters'],
  },
  {
    id: 'cookware_set',
    categoryId: 'cooking_food',
    label: 'Batería de cocina',
    type: 'conditional',
    priority: 'medium',
    conditions: {
      accommodationIn: ['tent', 'caravan'],
    },
    itemIds: ['pot_set', 'pan_main'],
    notes: 'Revisa la cantidad si viajan cuatro o más personas.',
  },
  {
    id: 'tableware_set',
    categoryId: 'cooking_food',
    label: 'Vajilla y cubiertos',
    type: 'essential',
    priority: 'medium',
    conditions: {
      accommodationIn: ['tent', 'caravan', 'bungalow', 'camping_cabin'],
    },
    itemIds: ['plates_bowls', 'cups_set', 'cutlery_set'],
  },
  {
    id: 'cooking_tools',
    categoryId: 'cooking_food',
    label: 'Utensilios de cocina',
    type: 'conditional',
    priority: 'medium',
    conditions: {
      accommodationIn: ['tent', 'caravan'],
      peopleCountIn: ['3', '4_plus'],
    },
    itemIds: ['knife_board_set', 'spatula_tongs', 'can_opener'],
  },
  {
    id: 'coffee_tea_kit',
    categoryId: 'cooking_food',
    label: 'Kit de café o té',
    type: 'extra',
    priority: 'low',
    conditions: {
      tripDurationIn: ['medium', 'long'],
    },
    itemIds: ['favorite_mug', 'coffee_press', 'tea_bags'],
  },
  {
    id: 'water_storage',
    categoryId: 'cooking_food',
    label: 'Reserva de agua',
    type: 'conditional',
    priority: 'high',
    conditions: {
      accommodationIn: ['tent', 'caravan'],
    },
    itemIds: ['water_jerrycan', 'refill_bag'],
    notes: 'Revisa la cantidad si viajan cuatro o más personas.',
  },
  {
    id: 'personal_water_bottle',
    categoryId: 'cooking_food',
    label: 'Botella o cantimplora',
    type: 'essential',
    priority: 'high',
    itemIds: ['water_bottle_main'],
  },
  {
    id: 'water_purification',
    categoryId: 'cooking_food',
    label: 'Purificación de agua',
    type: 'conditional',
    priority: 'medium',
    conditions: {
      accommodationIn: ['tent', 'caravan'],
      tripDurationIn: ['medium', 'long'],
    },
    itemIds: ['purification_tablets', 'filter_straw'],
  },
  {
    id: 'cooler',
    categoryId: 'cooking_food',
    label: 'Nevera portátil',
    type: 'conditional',
    priority: 'medium',
    conditions: {
      tripDurationIn: ['medium', 'long'],
    },
    itemIds: ['cooler_box', 'ice_packs'],
  },
  {
    id: 'main_food_supplies',
    categoryId: 'cooking_food',
    label: 'Comida principal planificada',
    type: 'essential',
    priority: 'high',
    itemIds: ['meal_plan', 'breakfast_food', 'main_meals'],
    notes: 'Ajusta la cantidad según la duración y el grupo.',
  },
  {
    id: 'snacks_pack',
    categoryId: 'cooking_food',
    label: 'Pack de snacks',
    type: 'essential',
    priority: 'medium',
    itemIds: ['energy_bars', 'fruit_snacks', 'nuts_pack'],
  },
  {
    id: 'condiments_pack',
    categoryId: 'cooking_food',
    label: 'Condimentos básicos',
    type: 'extra',
    priority: 'low',
    conditions: {
      tripDurationIn: ['medium', 'long'],
    },
    itemIds: ['salt_pepper', 'oil_small', 'sauce_pack'],
  },
  {
    id: 'base_layers_spares',
    categoryId: 'clothing_footwear',
    label: 'Ropa base y recambios',
    type: 'essential',
    priority: 'high',
    itemIds: ['socks_spares', 'underwear_spares', 'tshirt_spares'],
    notes: 'Ajusta la cantidad según la duración y el grupo.',
  },
  {
    id: 'rain_protection',
    categoryId: 'clothing_footwear',
    label: 'Protección para lluvia',
    type: 'essential',
    priority: 'medium',
    itemIds: ['rain_jacket', 'packable_rain_pants'],
  },
  {
    id: 'insulation_layer',
    categoryId: 'clothing_footwear',
    label: 'Capa de abrigo',
    type: 'conditional',
    priority: 'medium',
    conditions: {
      tripDurationIn: ['medium', 'long'],
    },
    itemIds: ['fleece_layer', 'warm_midlayer'],
  },
  {
    id: 'quick_dry_clothes',
    categoryId: 'clothing_footwear',
    label: 'Ropa de secado rápido',
    type: 'conditional',
    priority: 'medium',
    conditions: {
      tripDurationIn: ['medium', 'long'],
    },
    itemIds: ['quick_dry_top', 'quick_dry_bottom'],
  },
  {
    id: 'sleepwear',
    categoryId: 'clothing_footwear',
    label: 'Ropa para dormir',
    type: 'essential',
    priority: 'low',
    conditions: {
      accommodationIn: ['caravan', 'bungalow', 'camping_cabin'],
    },
    itemIds: ['sleep_set'],
  },
  {
    id: 'main_footwear',
    categoryId: 'clothing_footwear',
    label: 'Calzado principal',
    type: 'essential',
    priority: 'high',
    itemIds: ['hiking_shoes'],
  },
  {
    id: 'camp_footwear',
    categoryId: 'clothing_footwear',
    label: 'Calzado de campamento',
    type: 'extra',
    priority: 'low',
    conditions: {
      accommodationIn: ['tent', 'caravan'],
      tripDurationIn: ['medium', 'long'],
    },
    itemIds: ['camp_slides'],
  },
  {
    id: 'sun_head_protection',
    categoryId: 'clothing_footwear',
    label: 'Gorra, sombrero y gafas',
    type: 'conditional',
    priority: 'medium',
    itemIds: ['cap_or_hat', 'sunglasses'],
  },
  {
    id: 'cold_accessories',
    categoryId: 'clothing_footwear',
    label: 'Accesorios de frío',
    type: 'conditional',
    priority: 'medium',
    conditions: {
      tripDurationIn: ['long'],
    },
    itemIds: ['beanie', 'light_gloves'],
  },
  {
    id: 'power_bank',
    categoryId: 'energy_lighting_navigation',
    label: 'Batería externa',
    type: 'conditional',
    priority: 'medium',
    conditions: {
      tripDurationIn: ['medium', 'long'],
    },
    itemIds: ['power_bank_main', 'charging_cables'],
  },
  {
    id: 'portable_power_station',
    categoryId: 'energy_lighting_navigation',
    label: 'Estación de energía portátil',
    type: 'extra',
    priority: 'low',
    conditions: {
      accommodationIn: ['caravan', 'bungalow', 'camping_cabin'],
      tripDurationIn: ['medium', 'long'],
    },
    itemIds: ['power_station_main'],
  },
  {
    id: 'portable_solar_panel',
    categoryId: 'energy_lighting_navigation',
    label: 'Panel solar portátil',
    type: 'extra',
    priority: 'low',
    conditions: {
      accommodationIn: ['tent', 'caravan'],
      tripDurationIn: ['long'],
    },
    itemIds: ['solar_panel_foldable'],
  },
  {
    id: 'headlamp',
    categoryId: 'energy_lighting_navigation',
    label: 'Frontal',
    type: 'essential',
    priority: 'high',
    conditions: {
      accommodationIn: ['tent', 'caravan'],
    },
    itemIds: ['headlamp_main', 'headlamp_batteries'],
  },
  {
    id: 'camp_lantern',
    categoryId: 'energy_lighting_navigation',
    label: 'Lámpara de campamento',
    type: 'conditional',
    priority: 'medium',
    conditions: {
      accommodationIn: ['tent', 'caravan'],
    },
    itemIds: ['lantern_main'],
  },
  {
    id: 'flashlight_backup',
    categoryId: 'energy_lighting_navigation',
    label: 'Linterna de respaldo',
    type: 'essential',
    priority: 'medium',
    itemIds: ['flashlight_main', 'spare_batteries'],
  },
  {
    id: 'phone_offline_maps',
    categoryId: 'energy_lighting_navigation',
    label: 'Teléfono con mapas sin conexión',
    type: 'essential',
    priority: 'high',
    itemIds: ['offline_maps_downloaded', 'phone_cable'],
  },
  {
    id: 'navigation_backup',
    categoryId: 'energy_lighting_navigation',
    label: 'Navegación de respaldo',
    type: 'conditional',
    priority: 'medium',
    conditions: {
      accommodationIn: ['tent', 'caravan'],
      tripDurationIn: ['long'],
    },
    itemIds: ['paper_map', 'compass_main'],
  },
  {
    id: 'first_aid',
    categoryId: 'health_safety_repair',
    label: 'Botiquín',
    type: 'essential',
    priority: 'high',
    itemIds: ['first_aid_pouch'],
  },
  {
    id: 'personal_medication',
    categoryId: 'health_safety_repair',
    label: 'Medicación personal',
    type: 'essential',
    priority: 'high',
    itemIds: ['daily_medication', 'prescription_copy'],
  },
  {
    id: 'sun_skin_protection',
    categoryId: 'health_safety_repair',
    label: 'Protección solar y de piel',
    type: 'essential',
    priority: 'medium',
    itemIds: ['sunscreen_main', 'lip_balm'],
  },
  {
    id: 'insect_repellent',
    categoryId: 'health_safety_repair',
    label: 'Repelente de insectos',
    type: 'conditional',
    priority: 'medium',
    conditions: {
      accommodationIn: ['tent', 'caravan', 'bungalow'],
    },
    itemIds: ['repellent_spray', 'bite_relief'],
  },
  {
    id: 'multi_tool',
    categoryId: 'health_safety_repair',
    label: 'Multiherramienta',
    type: 'conditional',
    priority: 'medium',
    conditions: {
      accommodationIn: ['tent', 'caravan'],
    },
    itemIds: ['multi_tool_main'],
  },
  {
    id: 'repair_kit',
    categoryId: 'health_safety_repair',
    label: 'Kit de reparación',
    type: 'conditional',
    priority: 'medium',
    conditions: {
      accommodationIn: ['tent', 'caravan'],
    },
    itemIds: ['repair_tape', 'patch_kit', 'spare_cord'],
  },
  {
    id: 'camp_tools',
    categoryId: 'health_safety_repair',
    label: 'Herramientas de campamento',
    type: 'conditional',
    priority: 'low',
    conditions: {
      accommodationIn: ['tent'],
      tripDurationIn: ['medium', 'long'],
    },
    itemIds: ['folding_shovel', 'camp_brush'],
  },
  {
    id: 'emergency_signal',
    categoryId: 'health_safety_repair',
    label: 'Señal de emergencia',
    type: 'conditional',
    priority: 'low',
    conditions: {
      accommodationIn: ['tent', 'caravan'],
      tripDurationIn: ['long'],
    },
    itemIds: ['emergency_whistle', 'emergency_blanket'],
  },
  {
    id: 'fire_safety',
    categoryId: 'health_safety_repair',
    label: 'Seguridad contra incendios',
    type: 'conditional',
    priority: 'medium',
    conditions: {
      accommodationIn: ['tent', 'caravan'],
    },
    itemIds: ['fire_gloves', 'extinguisher_small'],
  },
  {
    id: 'wash_kit',
    categoryId: 'hygiene_cleanup',
    label: 'Kit de aseo',
    type: 'essential',
    priority: 'medium',
    itemIds: ['soap_small', 'face_wash', 'deodorant'],
  },
  {
    id: 'dental_kit',
    categoryId: 'hygiene_cleanup',
    label: 'Kit dental',
    type: 'essential',
    priority: 'medium',
    itemIds: ['toothbrush_main', 'toothpaste', 'dental_floss'],
  },
  {
    id: 'quick_dry_towel',
    categoryId: 'hygiene_cleanup',
    label: 'Toalla de secado rápido',
    type: 'conditional',
    priority: 'medium',
    conditions: {
      tripDurationIn: ['medium', 'long'],
    },
    itemIds: ['quick_dry_towel_main'],
  },
  {
    id: 'toilet_paper_tissues',
    categoryId: 'hygiene_cleanup',
    label: 'Papel higiénico y pañuelos',
    type: 'essential',
    priority: 'medium',
    itemIds: ['toilet_paper_main', 'tissues_pack'],
  },
  {
    id: 'sanitizer_wipes',
    categoryId: 'hygiene_cleanup',
    label: 'Gel y toallitas',
    type: 'essential',
    priority: 'medium',
    itemIds: ['sanitizer_gel', 'wet_wipes'],
  },
  {
    id: 'dishwashing_kit',
    categoryId: 'hygiene_cleanup',
    label: 'Kit de lavado',
    type: 'conditional',
    priority: 'medium',
    conditions: {
      accommodationIn: ['tent', 'caravan'],
    },
    itemIds: ['dish_soap', 'sponge_main', 'wash_basin'],
  },
  {
    id: 'trash_bags',
    categoryId: 'hygiene_cleanup',
    label: 'Bolsas de basura',
    type: 'essential',
    priority: 'medium',
    itemIds: ['trash_bags_roll'],
  },
  {
    id: 'foldable_trash_bin',
    categoryId: 'hygiene_cleanup',
    label: 'Cubo plegable de basura',
    type: 'extra',
    priority: 'low',
    conditions: {
      accommodationIn: ['tent', 'caravan'],
      peopleCountIn: ['3', '4_plus'],
    },
    itemIds: ['foldable_trash_bin_main'],
  },
  {
    id: 'identity_health_docs',
    categoryId: 'documents_money',
    label: 'Identificación y tarjeta sanitaria',
    type: 'essential',
    priority: 'high',
    itemIds: ['id_card', 'health_card'],
  },
  {
    id: 'booking_permits',
    categoryId: 'documents_money',
    label: 'Reservas y permisos',
    type: 'essential',
    priority: 'high',
    itemIds: ['booking_confirmation', 'access_permit'],
  },
  {
    id: 'cash_cards',
    categoryId: 'documents_money',
    label: 'Dinero, tarjetas y llaves',
    type: 'essential',
    priority: 'high',
    itemIds: ['wallet_cash', 'bank_cards', 'vehicle_keys'],
  },
  {
    id: 'reading_pack',
    categoryId: 'leisure',
    label: 'Lectura ligera',
    type: 'extra',
    priority: 'low',
    conditions: {
      tripDurationIn: ['medium', 'long'],
    },
    itemIds: ['book_or_kindle'],
  },
  {
    id: 'games_pack',
    categoryId: 'leisure',
    label: 'Juegos de viaje',
    type: 'extra',
    priority: 'low',
    conditions: {
      tripDurationIn: ['medium', 'long'],
      peopleCountIn: ['2', '3', '4_plus'],
    },
    itemIds: ['card_deck', 'compact_game'],
  },
  {
    id: 'photo_observation',
    categoryId: 'leisure',
    label: 'Cámara o prismáticos',
    type: 'extra',
    priority: 'low',
    conditions: {
      tripDurationIn: ['medium', 'long'],
    },
    itemIds: ['camera_main', 'binoculars_main'],
  },
  {
    id: 'journal_pack',
    categoryId: 'leisure',
    label: 'Cuaderno de viaje',
    type: 'extra',
    priority: 'low',
    conditions: {
      tripDurationIn: ['long'],
    },
    itemIds: ['journal_notebook', 'pen_set'],
  },
  {
    id: 'fishing_pack',
    categoryId: 'leisure',
    label: 'Equipo de pesca',
    type: 'conditional',
    priority: 'low',
    conditions: {
      tripDurationIn: ['medium', 'long'],
    },
    itemIds: ['fishing_rod_basic', 'fishing_tackle', 'fishing_permit_check'],
  },
  {
    id: 'pet_food',
    categoryId: 'pet',
    label: 'Comida de mascota',
    type: 'essential',
    priority: 'high',
    conditions: {
      requiresPet: true,
    },
    itemIds: ['pet_food_portions'],
  },
  {
    id: 'pet_bowl',
    categoryId: 'pet',
    label: 'Cuenco de mascota',
    type: 'essential',
    priority: 'medium',
    conditions: {
      requiresPet: true,
    },
    itemIds: ['pet_food_bowl', 'pet_water_bowl'],
  },
  {
    id: 'pet_leash',
    categoryId: 'pet',
    label: 'Correa y arnés',
    type: 'essential',
    priority: 'high',
    conditions: {
      requiresPet: true,
    },
    itemIds: ['pet_leash_main', 'pet_harness'],
  },
  {
    id: 'pet_rest_kit',
    categoryId: 'pet',
    label: 'Cama o manta de mascota',
    type: 'conditional',
    priority: 'medium',
    conditions: {
      requiresPet: true,
      tripDurationIn: ['medium', 'long'],
    },
    itemIds: ['pet_blanket', 'pet_bed'],
  },
  {
    id: 'pet_cleanup',
    categoryId: 'pet',
    label: 'Limpieza de mascota',
    type: 'essential',
    priority: 'medium',
    conditions: {
      requiresPet: true,
    },
    itemIds: ['pet_waste_bags', 'pet_towel'],
  },
  {
    id: 'pet_medication',
    categoryId: 'pet',
    label: 'Medicación de mascota',
    type: 'essential',
    priority: 'high',
    conditions: {
      requiresPet: true,
    },
    itemIds: ['pet_medication_dose'],
  },
] satisfies CatalogPool[];
