import type { TaskTemplate } from '@/types/trip';

const essentialPoints = 10;
const extraPoints = 5;

export const taskCatalog: TaskTemplate[] = [
  {
    id: 'reservation_docs',
    title: 'Reservation documents',
    category: 'essentials',
    basePriority: 'high',
    type: 'essential',
    basePoints: essentialPoints,
    description: 'Booking confirmation, campsite details and arrival notes.',
  },
  {
    id: 'phone',
    title: 'Phone',
    category: 'essentials',
    basePriority: 'high',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'charger',
    title: 'Charger',
    category: 'essentials',
    basePriority: 'high',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'wallet_keys',
    title: 'Wallet and keys',
    category: 'essentials',
    basePriority: 'high',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'water',
    title: 'Water',
    category: 'essentials',
    basePriority: 'high',
    type: 'essential',
    basePoints: essentialPoints,
    description: 'Enough water for travel, setup and the first hours on site.',
  },
  {
    id: 'sleeping_bag',
    title: 'Sleeping bag',
    category: 'sleep',
    basePriority: 'high',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'pillow',
    title: 'Pillow',
    category: 'sleep',
    basePriority: 'medium',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'sleeping_pad',
    title: 'Sleeping pad',
    category: 'sleep',
    basePriority: 'high',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'blanket',
    title: 'Blanket',
    category: 'sleep',
    basePriority: 'medium',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'tent',
    title: 'Tent',
    category: 'shelter',
    basePriority: 'high',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'stakes',
    title: 'Stakes',
    category: 'shelter',
    basePriority: 'high',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'tarp',
    title: 'Tarp',
    category: 'shelter',
    basePriority: 'medium',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'stove',
    title: 'Portable stove',
    category: 'cooking',
    basePriority: 'medium',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'fuel',
    title: 'Fuel',
    category: 'cooking',
    basePriority: 'medium',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'cookware',
    title: 'Cookware',
    category: 'cooking',
    basePriority: 'medium',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'planned_food',
    title: 'Planned food',
    category: 'food',
    basePriority: 'high',
    type: 'essential',
    basePoints: essentialPoints,
    description: 'Meals considered before leaving, not improvised at the last minute.',
  },
  {
    id: 'snacks',
    title: 'Snacks',
    category: 'food',
    basePriority: 'medium',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'cooler',
    title: 'Cooler',
    category: 'food',
    basePriority: 'medium',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'change_clothes',
    title: 'Change of clothes',
    category: 'clothing',
    basePriority: 'high',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'warm_clothes',
    title: 'Warm clothes',
    category: 'clothing',
    basePriority: 'medium',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'rain_jacket',
    title: 'Rain jacket',
    category: 'clothing',
    basePriority: 'medium',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'toothbrush',
    title: 'Toothbrush',
    category: 'hygiene',
    basePriority: 'medium',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'towel',
    title: 'Towel',
    category: 'hygiene',
    basePriority: 'medium',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'toilet_paper',
    title: 'Toilet paper',
    category: 'hygiene',
    basePriority: 'medium',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'sunscreen',
    title: 'Sunscreen',
    category: 'hygiene',
    basePriority: 'medium',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'flashlight',
    title: 'Flashlight',
    category: 'safety',
    basePriority: 'high',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'first_aid',
    title: 'First aid kit',
    category: 'safety',
    basePriority: 'high',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'power_bank',
    title: 'Power bank',
    category: 'safety',
    basePriority: 'medium',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'pet_food',
    title: 'Pet food',
    category: 'pet',
    basePriority: 'high',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'pet_bowl',
    title: 'Pet bowl',
    category: 'pet',
    basePriority: 'medium',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'pet_bed',
    title: 'Pet bed',
    category: 'pet',
    basePriority: 'medium',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'pet_leash',
    title: 'Pet leash',
    category: 'pet',
    basePriority: 'high',
    type: 'essential',
    basePoints: essentialPoints,
  },
  {
    id: 'camp_chair',
    title: 'Camp chair',
    category: 'comfort_extras',
    basePriority: 'medium',
    type: 'extra',
    basePoints: extraPoints,
  },
  {
    id: 'ambient_light',
    title: 'Ambient light',
    category: 'comfort_extras',
    basePriority: 'low',
    type: 'extra',
    basePoints: extraPoints,
  },
  {
    id: 'speaker',
    title: 'Portable speaker',
    category: 'comfort_extras',
    basePriority: 'low',
    type: 'extra',
    basePoints: extraPoints,
  },
  {
    id: 'special_breakfast',
    title: 'Special breakfast',
    category: 'comfort_extras',
    basePriority: 'low',
    type: 'extra',
    basePoints: extraPoints,
  },
];
